version: '3.8'

services:
  producer1:
    container_name: producer1
    build:
      context: .
      dockerfile: Dockerfile.prod1
    environment:
      PYTHONUNBUFFERED: "1"
    networks:
      kafka-network:
        ipv4_address: 192.168.1.12

networks:
  kafka-network:
    external: true
    driver: bridge

