version: '3.8'

services:
  producer2:
    container_name: producer2
    build:
      context: .
      dockerfile: Dockerfile.prod2
    environment:
      PYTHONUNBUFFERED: "1"
    networks:
      kafka-network:
        ipv4_address: 192.168.1.13

networks:
  kafka-network:
    external: true
    driver: bridge